# Clinical Pipeline Explorer - Shiny Application
# Interactive data viewer for ADaM datasets generated by the pipeline

library(shiny)
library(DT)
library(dplyr)
library(ggplot2)

# Function to safely load datasets
load_dataset <- function(dataset_name) {
  # Try multiple file formats
  paths <- c(
    file.path("../outputs/adam", paste0(dataset_name, ".sas7bdat")),
    file.path("../data/adam", paste0(dataset_name, ".sas7bdat")),
    file.path("../outputs/adam", paste0(dataset_name, ".csv")),
    file.path("../data/adam", paste0(dataset_name, ".csv"))
  )
  
  for (path in paths) {
    if (file.exists(path)) {
      if (grepl("\\.sas7bdat$", path)) {
        if (requireNamespace("haven", quietly = TRUE)) {
          return(haven::read_sas(path))
        }
      } else if (grepl("\\.csv$", path)) {
        return(read.csv(path, stringsAsFactors = FALSE))
      }
    }
  }
  
  # Return demo data if file not found
  return(data.frame(
    Note = "Dataset not found. Run the pipeline to generate outputs.",
    stringsAsFactors = FALSE
  ))
}

# Available datasets
available_datasets <- c("ADSL", "ADAE", "ADLB", "ADVS", "ADCM")

# UI Definition
ui <- fluidPage(
  titlePanel("Clinical Pipeline Data Explorer"),
  
  sidebarLayout(
    sidebarPanel(
      width = 3,
      
      h4("Dataset Selection"),
      selectInput(
        "dataset", 
        "Choose ADaM Dataset:", 
        choices = available_datasets,
        selected = "ADSL"
      ),
      
      hr(),
      
      h4("Export Options"),
      downloadButton("download_csv", "Download CSV"),
      
      hr(),
      
      h4("About"),
      p("This app provides interactive exploration of ADaM datasets 
        generated by the clinical pipeline."),
      p(strong("Features:")),
      tags$ul(
        tags$li("Interactive data tables with search/filter"),
        tags$li("Summary statistics"),
        tags$li("Data export to CSV"),
        tags$li("Column distribution plots")
      )
    ),
    
    mainPanel(
      width = 9,
      
      tabsetPanel(
        id = "tabs",
        
        tabPanel(
          "Data Table",
          br(),
          DTOutput("data_table")
        ),
        
        tabPanel(
          "Summary",
          br(),
          verbatimTextOutput("data_summary"),
          br(),
          h4("Dataset Dimensions"),
          textOutput("dimensions")
        ),
        
        tabPanel(
          "Visualizations",
          br(),
          selectInput("plot_column", "Select Column:", choices = NULL),
          plotOutput("distribution_plot", height = "400px")
        )
      )
    )
  )
)

# Server Logic
server <- function(input, output, session) {
  
  # Reactive dataset loading
  dataset <- reactive({
    req(input$dataset)
    load_dataset(input$dataset)
  })
  
  # Update plot column choices when dataset changes
  observe({
    df <- dataset()
    if (ncol(df) > 0) {
      updateSelectInput(
        session, 
        "plot_column",
        choices = names(df),
        selected = names(df)[1]
      )
    }
  })
  
  # Data table output
  output$data_table <- renderDT({
    datatable(
      dataset(), 
      filter = 'top',
      options = list(
        pageLength = 25,
        scrollX = TRUE,
        autoWidth = TRUE
      ),
      rownames = FALSE
    )
  })
  
  # Summary statistics
  output$data_summary <- renderPrint({
    summary(dataset())
  })
  
  # Dataset dimensions
  output$dimensions <- renderText({
    df <- dataset()
    paste0(
      "Rows: ", nrow(df), " | ",
      "Columns: ", ncol(df)
    )
  })
  
  # Distribution plot
  output$distribution_plot <- renderPlot({
    req(input$plot_column)
    df <- dataset()
    
    if (!input$plot_column %in% names(df)) {
      return(NULL)
    }
    
    col_data <- df[[input$plot_column]]
    
    # Handle numeric vs categorical
    if (is.numeric(col_data)) {
      ggplot(df, aes(x = .data[[input$plot_column]])) +
        geom_histogram(bins = 30, fill = "steelblue", alpha = 0.7) +
        theme_minimal() +
        labs(
          title = paste("Distribution of", input$plot_column),
          x = input$plot_column,
          y = "Count"
        )
    } else {
      # Count top categories
      top_cats <- df %>%
        count(.data[[input$plot_column]]) %>%
        arrange(desc(n)) %>%
        head(20)
      
      ggplot(top_cats, aes(x = reorder(.data[[input$plot_column]], n), y = n)) +
        geom_col(fill = "steelblue", alpha = 0.7) +
        coord_flip() +
        theme_minimal() +
        labs(
          title = paste("Top 20 Values:", input$plot_column),
          x = input$plot_column,
          y = "Count"
        )
    }
  })
  
  # Download handler
  output$download_csv <- downloadHandler(
    filename = function() {
      paste0(input$dataset, "_", Sys.Date(), ".csv")
    },
    content = function(file) {
      write.csv(dataset(), file, row.names = FALSE)
    }
  )
}

# Run the application
shinyApp(ui = ui, server = server)
