# Clinical Pipeline Explorer - Shiny Application
# Interactive portfolio dashboard and data explorer for ADaM datasets

library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)
library(ggplot2)
library(purrr)

source("app/modules/portfolio_dashboard.R")

# Function to safely load datasets
load_dataset <- function(dataset_name) {
  # Try multiple file formats
  paths <- c(
    file.path("../outputs/adam", paste0(dataset_name, ".sas7bdat")),
    file.path("../data/adam", paste0(dataset_name, ".sas7bdat")),
    file.path("../outputs/adam", paste0(dataset_name, ".csv")),
    file.path("../data/adam", paste0(dataset_name, ".csv"))
  )

  for (path in paths) {
    if (file.exists(path)) {
      if (grepl("\\.sas7bdat$", path)) {
        if (requireNamespace("haven", quietly = TRUE)) {
          return(haven::read_sas(path))
        }
      } else if (grepl("\\.csv$", path)) {
        return(read.csv(path, stringsAsFactors = FALSE))
      }
    }
  }

  # Return demo data if file not found
  return(data.frame(
    Note = "Dataset not found. Run the pipeline to generate outputs.",
    stringsAsFactors = FALSE
  ))
}

# Available datasets
available_datasets <- c("ADSL", "ADAE", "ADLB", "ADVS", "ADCM")

ui <- dashboardPage(
  dashboardHeader(title = "Clinical Pipeline Explorer"),
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("Portfolio Overview", tabName = "portfolio", icon = icon("briefcase")),
      menuItem("Data Explorer", tabName = "data", icon = icon("table")),
      menuItem("TLF Viewer", tabName = "tlf", icon = icon("file-alt"))
    )
  ),
  
  dashboardBody(
    tabItems(
      tabItem(tabName = "portfolio",
              portfolio_dashboard_UI("portfolio")),
      
      tabItem(tabName = "data",
              fluidRow(
                box(width = 4, title = "Dataset Selection", status = "primary", solidHeader = TRUE,
                    selectInput(
                      "dataset",
                      "Choose ADaM Dataset:",
                      choices = available_datasets,
                      selected = "ADSL"
                    ),
                    hr(),
                    h4("Export Options"),
                    downloadButton("download_csv", "Download CSV"),
                    hr(),
                    h4("About"),
                    p("Interactive exploration of ADaM datasets generated by the clinical pipeline."),
                    tags$ul(
                      tags$li("Interactive data tables with search/filter"),
                      tags$li("Summary statistics"),
                      tags$li("Data export to CSV"),
                      tags$li("Column distribution plots")
                    )
                ),
                box(width = 8, title = "Dataset Explorer", status = "primary", solidHeader = TRUE,
                    tabBox(width = 12,
                           tabPanel("Data Table",
                                    DTOutput("data_table")),
                           tabPanel("Summary",
                                    verbatimTextOutput("data_summary"),
                                    br(),
                                    h4("Dataset Dimensions"),
                                    textOutput("dimensions")),
                           tabPanel("Visualizations",
                                    selectInput("plot_column", "Select Column:", choices = NULL),
                                    plotOutput("distribution_plot", height = "400px"))
                    )
                )
              )),
      
      tabItem(tabName = "tlf",
              fluidRow(
                box(width = 12, title = "TLF Viewer", status = "info", solidHeader = TRUE,
                    p("TLF viewer integration placeholder for future enhancements."))
              ))
    )
  )
)

server <- function(input, output, session) {
  portfolio_dashboard_Server("portfolio")

  # Reactive dataset loading
  dataset <- reactive({
    req(input$dataset)
    load_dataset(input$dataset)
  })

  # Update plot column choices when dataset changes
  observe({
    df <- dataset()
    if (ncol(df) > 0) {
      updateSelectInput(
        session,
        "plot_column",
        choices = names(df),
        selected = names(df)[1]
      )
    }
  })

  # Data table output
  output$data_table <- renderDT({
    datatable(
      dataset(),
      filter = 'top',
      options = list(
        pageLength = 25,
        scrollX = TRUE,
        autoWidth = TRUE
      ),
      rownames = FALSE
    )
  })

  # Summary statistics
  output$data_summary <- renderPrint({
    summary(dataset())
  })

  # Dataset dimensions
  output$dimensions <- renderText({
    df <- dataset()
    paste0(
      "Rows: ", nrow(df), " | ",
      "Columns: ", ncol(df)
    )
  })

  # Distribution plot
  output$distribution_plot <- renderPlot({
    req(input$plot_column)
    df <- dataset()

    if (!input$plot_column %in% names(df)) {
      return(NULL)
    }

    col_data <- df[[input$plot_column]]

    # Handle numeric vs categorical
    if (is.numeric(col_data)) {
      ggplot(df, aes(x = .data[[input$plot_column]])) +
        geom_histogram(bins = 30, fill = "steelblue", alpha = 0.7) +
        theme_minimal() +
        labs(
          title = paste("Distribution of", input$plot_column),
          x = input$plot_column,
          y = "Count"
        )
    } else {
      top_cats <- df %>%
        count(.data[[input$plot_column]]) %>%
        arrange(desc(n)) %>%
        head(20)

      ggplot(top_cats, aes(x = reorder(.data[[input$plot_column]], n), y = n)) +
        geom_col(fill = "steelblue", alpha = 0.7) +
        coord_flip() +
        theme_minimal() +
        labs(
          title = paste("Top 20 Values:", input$plot_column),
          x = input$plot_column,
          y = "Count"
        )
    }
  })

  # Download handler
  output$download_csv <- downloadHandler(
    filename = function() {
      paste0(input$dataset, "_", Sys.Date(), ".csv")
    },
    content = function(file) {
      write.csv(dataset(), file, row.names = FALSE)
    }
  )
}

shinyApp(ui = ui, server = server)
