/****************************************************************************************
* Project:        Hybrid SAS Clinical Automation
* Description:    High-discipline SAS macro toolkit for auditable SDTM production.
* Author:         Generated by ChatGPT (gpt-5-codex)
* Date:           2025-11-10
*
* Overview:
*   - Version stamping for deterministic pipeline identification.
*   - Audit checkpoints that aggressively log pipeline stage outcomes.
*   - SDTM domain mapping with embedded data quality enforcement.
*   - Automated log interrogation utilities for regulatory review packs.
*   - QC macros that surface clinical data anomalies without human gating.
****************************************************************************************/

/*------------------------------------------------------------------------------
 1. Version stamping and initialization utilities
------------------------------------------------------------------------------*/
%macro VersionStamp();
    %global prog_ver user date_time;
    %let prog_ver = v2025.11.10;
    %let user = %sysfunc(getoption(sysuserid));
    %let date_time = %sysfunc(datetime(), datetime19.);
    %put === Pipeline Version: &prog_ver | User: &user | Launch: &date_time ===;
%mend VersionStamp;

/* Immediately stamp the session so that downstream logs are traceable. */
%VersionStamp();

/*------------------------------------------------------------------------------
 2. Audit checkpoints and SDTM mapping with ruthless QC
------------------------------------------------------------------------------*/
%macro AuditCheckpoint(stage, domain, status);
    %put NOTE: === [&stage] for domain &domain: &status ===;
%mend AuditCheckpoint;

%macro _resetFlag(flagName);
    %if %symexist(&flagName) %then %symdel &flagName / nowarn;
%mend _resetFlag;

%macro SDTM_Map_QC(raw=, sdtm=, domain=);
    %local dsid rc;
    %_resetFlag(qc_flag);
    %AuditCheckpoint(PRE-MAPPING, &domain, %str(SDTM transformation started. Brace for impact.));
    data &sdtm;
        set &raw;
        length _issue $200;
        if missing(subject_id) then do;
            _issue = "Missing subject_id. Just fire someone.";
            call symputx('qc_flag', _issue, 'G');
            put "ERROR: subject_id missing in &domain.. CAPA mandatory.";
            stop;
        end;
        if upcase(trtgrp) not in ('DRUG','PLACEBO') then do;
            _issue = catx(' ', 'Nonstandard trtgrp. Open deviation:', trtgrp);
            call symputx('qc_flag', _issue, 'G');
            put "ERROR: Bad trtgrp value in &domain.: " trtgrp;
            stop;
        end;
        keep subject_id trtgrp;
    run;

    %if %symexist(qc_flag) %then %do;
        %AuditCheckpoint(MAPPING-FAIL, &domain, %sysfunc(symget(qc_flag)));
    %end;
    %else %do;
        proc sort data=&sdtm nodupkey;
            by subject_id;
        run;
        %AuditCheckpoint(POST-MAPPING, &domain, %str(QC passed. Prepare for dual validation war.));
    %end;
%mend SDTM_Map_QC;

/*------------------------------------------------------------------------------
 3. SAS log file inspection utilities
------------------------------------------------------------------------------*/
%macro CheckSASLog(log=, issues_ds=logchk);
    data &issues_ds;
        infile "&log." truncover;
        length line $200.;
        input line $char200.;
        retain issue_type;
        issue_type = ' ';
        if find(upcase(line),'ERROR') then issue_type = 'ERROR';
        else if find(upcase(line),'WARNING') then issue_type = 'WARNING';
        else if find(upcase(line),'UNINITIALIZED') then issue_type = 'UNINITIALIZED';
        if issue_type ne ' ' then output;
    run;
    %let dsid = %sysfunc(open(&issues_ds));
    %let rc = %sysfunc(attrn(&dsid, nlobs));
    %let rc = %sysfunc(close(&dsid));
    %if &rc > 0 %then %do;
        title "SAS Log Issues - &log.";
        proc print data=&issues_ds noobs label;
            label issue_type = 'Category' line = 'Log Line';
        run;
        title;
    %end;
    %else %do;
        %put NOTE: === No anomalies detected in &log. ===;
    %end;
%mend CheckSASLog;

/*------------------------------------------------------------------------------
 4. Domain-specific QC (Adverse Events example)
------------------------------------------------------------------------------*/
%macro AEValidationCheck(ae_data=, result_ds=ae_qc_summary);
    %if ^%sysfunc(exist(&ae_data)) %then %do;
        %AuditCheckpoint(AE-QC, AE, %sysfunc(catx(%str( ), Dataset &ae_data not found. Abort mission.)));
        %return;
    %end;
    proc sql noprint;
        create table &result_ds as
        select
            sum(missing(ae_severity)) as missing_severity,
            sum(^missing(ae_severity) and upcase(ae_severity) not in ('MILD','MODERATE','SEVERE')) as invalid_severity,
            count(*) as total_records
        from &ae_data;
    quit;

    proc sort data=&ae_data out=_ae_unique nodupkey dupout=_ae_dups;
        by subject_id;
    run;

    %local duplicate;
    %let duplicate = 0;
    %if %sysfunc(exist(_ae_dups)) %then %do;
        data _null_;
            if 0 then set _ae_dups nobs=dupcount;
            call symputx('duplicate', dupcount, 'G');
            stop;
        run;
    %end;

    data &result_ds;
        set &result_ds;
        duplicate_records = &duplicate;
    run;

    %let dsid = %sysfunc(open(&result_ds));
    %let missing = %sysfunc(getvarn(&dsid, %sysfunc(varnum(&dsid, missing_severity))));
    %let invalid = %sysfunc(getvarn(&dsid, %sysfunc(varnum(&dsid, invalid_severity))));
    %let rc = %sysfunc(close(&dsid));
    %if (&missing > 0) %then %do;
        %AuditCheckpoint(AE-QC, AE, %sysfunc(catx(%str( ), Missing severity records:, &missing)));
    %end;
    %if (&invalid > 0) %then %do;
        %AuditCheckpoint(AE-QC, AE, %sysfunc(catx(%str( ), Invalid severity values:, &invalid)));
    %end;
    %if (&duplicate > 0) %then %do;
        %AuditCheckpoint(AE-QC, AE, %sysfunc(catx(%str( ), Duplicate subject rows:, &duplicate)));
    %end;
    %if (&missing = 0 and &invalid = 0) %then %do;
        %if (&duplicate = 0) %then %do;
            %AuditCheckpoint(AE-QC, AE, %str(AE checks passed. Nothing to see here.));
        %end;
    %end;
    proc datasets lib=work nolist;
        delete _ae_unique _ae_dups;
    quit;
%mend AEValidationCheck;

/*------------------------------------------------------------------------------
 5. Batch execution helper
------------------------------------------------------------------------------*/
%macro RunDomainPipeline(raw=, domain=DM, outlib=work);
    %local mapped;
    %let mapped = &outlib..&domain.;
    %SDTM_Map_QC(raw=&raw, sdtm=&mapped, domain=&domain);
    %if ^%symexist(qc_flag) %then %do;
        %AuditCheckpoint(BATCH, &domain, %str(Pipeline completed. Commit outputs to VC.));
    %end;
%mend RunDomainPipeline;

/* Example usage (commented out for inclusion in batch frameworks)
%RunDomainPipeline(raw=raw.dm, domain=DM, outlib=adam);
%CheckSASLog(log=/path/to/dm.log);
%AEValidationCheck(ae_data=adam.ae);
*/
